server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:

  application:
    name: hash
  dubbo:
    registry:
      address: zookeeper://192.168.1.59:2181
    protocol:
      name: dubbo
      port: 20880


